omni_bot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10
  left_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: base_link_rim_left_joint
    pid: {p: 1,i: 0,d: 0,i_clamp_min: -10,i_clamp_max: 10}
  right_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: base_link_rim_right_joint
    pid: {p: 1,i: 0,d: 0,i_clamp_min: -10,i_clamp_max: 10}
  front_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: base_link_rim_front_joint
    pid: {p: 1,i: 0,d: 0,i_clamp_min: -10,i_clamp_max: 10}
